export const stockData = [
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Complete',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '8 Jan',
            name: 'Do not disturb',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Complete',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '8 Jan',
            name: 'Do not disturb',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },{
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },{
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },{
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },{
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },{
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },
        {
            date: '14 Jan',
            name: 'Cleaning service',
            status: 'Pending',
            time: '10:15 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
        },
        {
            date: '13 Jan',
            name: 'Room Service Request',
            status: 'In-Process',
            time: '10:00 AM',
            details: 'Hello, I would like to',
            room: '401',
            timeservice: '5:30',
            
        },
        
        
    ]